queue:
    build: ./queue

server:
    build: ./server
    ports:
        - 8000:8000
    volumes:
        - ./scoring_engine:/opt/scoring_engine
    links:
        - queue

worker:
    build: ./server
    command: celery -A scoring_engine worker -l info
    volumes:
        - ./scoring_engine:/opt/scoring_engine
    links:
        - server
        - queue
